/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VisualizerImport } from './routes/visualizer'
import { Route as TestImport } from './routes/test'
import { Route as PlayerImport } from './routes/player'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VisualizerRoute = VisualizerImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const PlayerRoute = PlayerImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/test': typeof TestRoute
  '/visualizer': typeof VisualizerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/test': typeof TestRoute
  '/visualizer': typeof VisualizerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/test': typeof TestRoute
  '/visualizer': typeof VisualizerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player' | '/test' | '/visualizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player' | '/test' | '/visualizer'
  id: '__root__' | '/' | '/player' | '/test' | '/visualizer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRoute: typeof PlayerRoute
  TestRoute: typeof TestRoute
  VisualizerRoute: typeof VisualizerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRoute: PlayerRoute,
  TestRoute: TestRoute,
  VisualizerRoute: VisualizerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/player",
        "/test",
        "/visualizer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/player": {
      "filePath": "player.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/visualizer": {
      "filePath": "visualizer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
